services:
  php-fpm:
    image: php:8.3-fpm-alpine
    container_name: fluentlog-fpm
    working_dir: /app
    volumes:
      - ..:/app

  nginx:
    image: nginx:alpine
    container_name: fluentlog-nginx
    ports:
      - "8080:80"
    volumes:
      - ..:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm